import{formatIon}from"./chemistry.js?v=20260929-1700";import{createGame,nextChallenge,submit}from"./competition.js?v=20260929-1700";import storage from"./storage.js?v=20260929-1700";import{exportCSV}from"./teacher.js?v=20260929-1700";const $=id=>document.getElementById(id);const chemFormula=s=>esc(s).replace(/(\d+)/g,"<sub>$1</sub>");let config={durationSeconds:300,mode:"mixed",difficulty:"medium",family:"all",workMode:"practice",questionCount:10,...storage.getConfig()},game=createGame(config),timer=null;const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const FAMILY_OPTIONS={
 easy:[["all","Óxidos"]],
 medium:[["all","Todos los binarios"],["binary","Sales binarias y óxidos"]],
 hard:[["all","Todos hasta ternarios"],["binary","Sales binarias y óxidos"],["hydroxide","Hidróxidos"],["oxosalt","Oxosales"]],
 expert:[["all","Todos los compuestos"],["binary","Sales binarias y óxidos"],["hydroxide","Hidróxidos"],["oxosalt","Oxosales"],["acidsalt","Sales ácidas"]]
};
function syncFamilies(){
 const difficulty=$("difficulty").value,select=$("compoundFamily"),previous=select.value;
 select.innerHTML=FAMILY_OPTIONS[difficulty].map(([v,t])=>`<option value="${v}">${t}</option>`).join("");
 if(FAMILY_OPTIONS[difficulty].some(([v])=>v===previous))select.value=previous;
}
function syncWorkMode(){
 const m=$("workMode").value;
 $("examQuestionsLabel").classList.toggle("hidden",m!=="exam");
 $("timeLabel").classList.toggle("hidden",m==="learn"||m==="exam");
 $("modeHelp").innerHTML=m==="learn"?"<b>📘 Aprender:</b> sin tiempo ni presión. Puedes utilizar pistas y consultar la explicación paso a paso.":m==="exam"?"<b>📝 Examen:</b> número cerrado de preguntas. No hay pistas ni explicaciones durante la prueba y la corrección se muestra al finalizar.":"<b>🎯 Practicar:</b> puntos, rachas, tiempo, pistas y explicaciones como en el juego habitual.";
}
function applyWorkMode(){
 const m=game.config.workMode||"practice";
 $("learningModeBanner").textContent=m==="learn"?"📘 Modo Aprender":m==="exam"?`📝 Modo Examen · Pregunta ${Math.min(game.answered+1,game.config.questionCount)} de ${game.config.questionCount}`:"🎯 Modo Practicar";
 $("hintButton").classList.toggle("hidden",m==="exam");
 $("explanationButton").classList.toggle("hidden",m==="exam");
 $("spinButton").classList.toggle("hidden",m==="exam");
 document.querySelector(".stats").classList.toggle("learning-stats",m==="learn");
}
function downloadExamReport(){
 if(!game.answers.length)return;
 const player=$("playerName").textContent||"Alumno",total=game.answers.length,ok=game.correct,pct=Math.round(ok*100/total),grade=(ok/total*10).toFixed(1);
 const labels={easy:"Fácil · óxidos",medium:"Medio · compuestos binarios",hard:"Difícil · hasta ternarios",expert:"Experto · todos los compuestos",mixed:"Mixto",formula:"Fórmula",stock:"Estado de oxidación",systematic:"Sistemática",all:"Todos"};
 const date=new Date();
 const rows=game.answers.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.question)}</td><td>${esc(x.answer)}</td><td>${x.correct?"Correcta":"Incorrecta"}</td><td>${esc(x.expected)}</td></tr>`).join("");
 const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Informe - ${esc(player)}</title><style>body{font-family:Arial,sans-serif;max-width:1000px;margin:35px auto;padding:0 25px;color:#172033}h1{color:#1d4ed8}.meta,.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0}.meta div,.summary div{padding:12px;background:#f1f5f9;border-radius:8px}.summary b{font-size:24px;display:block;color:#1d4ed8}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:8px;border:1px solid #cbd5e1;text-align:left}th{background:#e2e8f0}.foot{margin-top:25px;color:#64748b;font-size:12px}@media print{button{display:none}body{margin:0;max-width:none}}</style></head><body><h1>⚗ El juego de los iones</h1><h2>Informe de resultados · Modo Examen</h2><div class="meta"><div><b>Alumno</b><br>${esc(player)}</div><div><b>Fecha</b><br>${date.toLocaleString("es-ES")}</div><div><b>Nivel</b><br>${labels[game.config.difficulty]||game.config.difficulty}</div><div><b>Tipo</b><br>${labels[game.config.mode]||game.config.mode}</div><div><b>Familia</b><br>${labels[game.config.family]||game.config.family}</div><div><b>Preguntas</b><br>${total}</div></div><div class="summary"><div><b>${ok}/${total}</b>Aciertos</div><div><b>${pct}%</b>Porcentaje</div><div><b>${grade}/10</b>Calificación</div></div><h2>Detalle de respuestas</h2><table><tr><th>#</th><th>Pregunta</th><th>Respuesta del alumno</th><th>Resultado</th><th>Respuesta correcta</th></tr>${rows}</table><p class="foot">Informe generado automáticamente por El juego de los iones. Los datos se procesan localmente en el navegador.</p></body></html>`;
 const blob=new Blob([html],{type:"text/html;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");
 const safe=player.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"_");
 link.href=url;link.download=`Informe_iones_${safe}_${date.toISOString().slice(0,10)}.html`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function renderExamResult(){
 const total=game.answers.length,ok=game.correct,pct=total?Math.round(ok*100/total):0,grade=total?(ok/total*10).toFixed(1):"0.0";
 const rows=game.answers.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.question)}</td><td>${esc(x.answer)}</td><td>${x.correct?"✅":"❌ "+esc(x.expected)}</td></tr>`).join("");
 $("examResultContent").innerHTML=`<div class="exam-summary"><div><b>${ok}/${total}</b><span>Aciertos</span></div><div><b>${pct}%</b><span>Porcentaje</span></div><div><b>${grade}/10</b><span>Calificación</span></div></div><h3>Corrección</h3><div class="table-wrap"><table><tr><th>#</th><th>Pregunta</th><th>Tu respuesta</th><th>Resultado</th></tr>${rows}</table></div>`;
 view("examResult");
}
function view(id){if(!$(id))id="student";document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===id));if(id==="history")renderHistory();if(id==="ranking")renderRanking()}document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>view(b.dataset.view));
function showChallenge(){if(game.finished)return;if(game.config.workMode==="exam"&&game.answered>=game.config.questionCount){finish();return}const q=nextChallenge(game);applyWorkMode();const labels=document.querySelectorAll(".slot small");if(q.peroxide){labels[0].textContent=`METAL (+${q.cation.charge})`;labels[1].textContent="PERÓXIDO (O₂²⁻)";$("cationSymbol").innerHTML=`${q.cation.symbol}<sup>${q.cation.charge===1?"":q.cation.charge}+</sup>`;$("anionSymbol").innerHTML="O₂<sup>2−</sup>"}else if(q.metalHydride){labels[0].textContent=`METAL (+${q.cation.charge})`;labels[1].textContent="HIDRÓGENO (−1)";$("cationSymbol").innerHTML=`${q.cation.symbol}<sup>${q.cation.charge===1?"":q.cation.charge}+</sup>`;$("anionSymbol").innerHTML="H<sup>−</sup>"}else if(q.hydrogenSpecial){const upper=q.cation.charge<0;labels[0].textContent=upper?"HIDRÓGENO (−1)":"HIDRÓGENO (+1)";labels[1].textContent=upper?`ELEMENTO (+${q.anion.charge})`:`ELEMENTO (${q.anion.charge})`;$("cationSymbol").innerHTML=upper?"H<sup>−</sup>":"H<sup>+</sup>";$("anionSymbol").innerHTML=`${chemFormula(q.anion.symbol)}<sup>${Math.abs(q.anion.charge)===1?"":Math.abs(q.anion.charge)}${q.anion.charge>0?"+":"−"}</sup>`}else if(q.special){const fluor=q.anion.symbol==="F";labels[0].textContent=fluor?"OXÍGENO (+2)":"OXÍGENO (−2)";labels[1].textContent=fluor?"FLÚOR (−1)":`HALÓGENO (+${q.anion.charge})`;$("cationSymbol").innerHTML=fluor?"O<sup>2+</sup>":"O<sup>2−</sup>";$("anionSymbol").innerHTML=fluor?"F<sup>−</sup>":`${q.anion.symbol}<sup>${q.anion.charge===1?"":q.anion.charge}+</sup>`}else{labels[0].textContent="CATIÓN (+)";labels[1].textContent="ANIÓN (−)";$("cationSymbol").innerHTML=formatIon(q.cation);$("anionSymbol").innerHTML=formatIon(q.anion)}$("cationName").textContent="";$("anionName").textContent="";$("exerciseTitle").textContent=q.type==="formula"?"Formula el compuesto":q.type==="stock"?"Estado de oxidación":"Nomenclatura de composición";$("exerciseQuestion").innerHTML=chemFormula(q.question);$("answerInput").value="";$("feedback").textContent="";$("feedback").className="";$("explanationPanel").classList.add("hidden");$("answerInput").focus()}
function update(){applyWorkMode();$("score").textContent=game.config.workMode==="learn"?"—":game.score;$("correctAnswers").textContent=game.correct;$("streak").textContent=game.streak;const s=Math.max(0,game.remaining);$("timer").textContent=game.config.durationSeconds===0?"∞":`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function saveFinal(){if(game.saved)return;game.saved=true;storage.addScore({playerName:$("playerName").textContent,score:game.score,correct:game.correct,incorrect:game.incorrect,bestStreak:game.bestStreak,mode:game.config.mode,difficulty:game.config.difficulty})}
function finish(){if(game.finished)return;game.finished=true;clearInterval(timer);timer=null;if(game.config.workMode==="exam"){renderExamResult();return}if(game.config.workMode==="practice"){saveFinal();$("feedback").className="ok";$("feedback").textContent="⏱️ Partida terminada. La puntuación se ha guardado.";renderRanking()}}
function startTimer(){clearInterval(timer);timer=null;if(game.config.workMode!=="practice"||!game.config.durationSeconds)return;timer=setInterval(()=>{game.remaining--;update();if(game.remaining<=0)finish()},1000)}
$("spinButton").onclick=()=>{if(game.finished){game=createGame(config);update()}document.querySelectorAll(".slot").forEach(x=>x.classList.add("spinning"));setTimeout(()=>{document.querySelectorAll(".slot").forEach(x=>x.classList.remove("spinning"));showChallenge()},350);if(!timer)startTimer()};$("nextButton").onclick=showChallenge;
$("answerForm").onsubmit=e=>{e.preventDefault();if(!game.current||game.finished)return;const answer=$("answerInput").value,r=submit(game,answer);storage.addHistory({playerName:$("playerName").textContent,type:game.current.type,question:game.current.question,answer,expected:r.expected,correct:r.correct,formula:game.current.formula});$("feedback").className=r.correct?"ok":"bad";$("feedback").innerHTML=r.correct?`✅ Correcto · ${r.score} puntos`:`❌ <b>Revisa tu respuesta.</b><br><span class="diagnosis">${esc(r.diagnosis)}</span><br><span class="solution">Respuesta correcta: <b>${esc(r.expected)}</b></span>`;game.current.lastTeaching=r.teaching;
 if(game.config.workMode==="learn"&&!r.correct){$("explanationPanel").innerHTML="<h3>🧠 Vamos a aprenderlo</h3><div class=\"teaching-steps\">"+r.teaching.map(x=>`<p>${esc(x)}</p>`).join("")+"</div>";$("explanationPanel").classList.remove("hidden")}
 update();
 if(game.config.workMode==="exam"){ $("feedback").textContent="Respuesta registrada."; setTimeout(()=>{if(game.answered>=game.config.questionCount)finish();else showChallenge()},350)}
};
$("hintButton").onclick=()=>{if(game.current&&!game.finished)$("feedback").textContent=`Pista: cargas ${game.current.cation.charge>0?"+":""}${game.current.cation.charge} y ${game.current.anion.charge}`};$("explanationButton").onclick=()=>{if(!game.current)return;const steps=game.current.lastTeaching||game.current.explanation;$("explanationPanel").innerHTML="<h3>🧠 Explicación paso a paso</h3><div class=\"teaching-steps\">"+steps.map(x=>`<p>${esc(x)}</p>`).join("")+`</div><div class="answer-summary"><b>Fórmula:</b> ${chemFormula(game.current.formula)}<br><b>Estado de oxidación:</b> ${esc(game.current.stockName)}<br><b>Nomenclatura de composición/sistemática:</b> ${esc(game.current.systematicName||"No se pregunta en esta familia")}</div>`;$("explanationPanel").classList.remove("hidden")};
$("saveConfiguration").onclick=()=>{config={durationSeconds:$("workMode").value==="practice"?Number($("gameTime").value):0,mode:$("exerciseType").value,difficulty:$("difficulty").value,family:$("compoundFamily").value,workMode:$("workMode").value,questionCount:Number($("examQuestions").value)};storage.saveConfig(config);$("playerName").textContent=$("studentNameInput").value.trim()||"Alumno";clearInterval(timer);timer=null;game=createGame(config);update();view("student");showChallenge();startTimer()};$("resetGame").onclick=()=>{clearInterval(timer);timer=null;game=createGame(config);update();$("feedback").textContent=""};$("exportCsv").onclick=exportCSV;
function renderHistory(){const h=storage.getHistory().slice().reverse();$("historyList").innerHTML=h.length?`<table><tr><th>Alumno</th><th>Reto</th><th>Resultado</th></tr>${h.map(x=>`<tr><td>${esc(x.playerName)}</td><td>${esc(x.question)}</td><td>${x.correct?"✅":"❌"} ${esc(x.answer)}</td></tr>`).join("")}</table>`:"<p>Aún no hay ejercicios.</p>"}
function renderRanking(){const r=storage.ranking();$("rankingList").innerHTML=r.length?`<table><tr><th>#</th><th>Alumno</th><th>Total</th><th>Mejor</th></tr>${r.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.total}</td><td>${x.best}</td></tr>`).join("")}</table>`:"<p>Aún no hay puntuaciones.</p>"}$("clearHistory").onclick=()=>{if(confirm("¿Borrar el historial?")){storage.clearHistory();renderHistory()}};$("clearRanking").onclick=()=>{if(confirm("¿Borrar las puntuaciones?")){storage.clearScores();renderRanking()}};
$("downloadExamReport").onclick=downloadExamReport;$("difficulty").addEventListener("change",syncFamilies);$("workMode").addEventListener("change",syncWorkMode);$("newExam").onclick=()=>{view("teacher");$("workMode").value="exam";syncWorkMode()};$("backToTeacher").onclick=()=>view("teacher");syncFamilies();syncWorkMode();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));const p=new URLSearchParams(location.search);if(p.get("teams")==="1")document.body.classList.add("teams");if(p.get("view"))view(p.get("view"));update();showChallenge();