import{formatIon}from"./chemistry.js";import{createGame,nextChallenge,submit}from"./competition.js";import storage from"./storage.js";import{exportCSV}from"./teacher.js";const $=id=>document.getElementById(id);let config={durationSeconds:300,mode:"mixed",difficulty:"medium",family:"all",...storage.getConfig()},game=createGame(config),timer=null;const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function view(id){if(!$(id))id="student";document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===id));if(id==="history")renderHistory();if(id==="ranking")renderRanking()}document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>view(b.dataset.view));
function showChallenge(){if(game.finished)return;const q=nextChallenge(game);$("cationSymbol").innerHTML=formatIon(q.cation);$("cationName").textContent=q.cation.name;$("anionSymbol").innerHTML=formatIon(q.anion);$("anionName").textContent=q.anion.name;$("exerciseTitle").textContent=q.type==="formula"?"Formula el compuesto":q.type==="stock"?"Estado de oxidación":"Nomenclatura";$("exerciseQuestion").textContent=q.question;$("answerInput").value="";$("feedback").textContent="";$("feedback").className="";$("explanationPanel").classList.add("hidden");$("answerInput").focus()}
function update(){$("score").textContent=game.score;$("correctAnswers").textContent=game.correct;$("streak").textContent=game.streak;const s=Math.max(0,game.remaining);$("timer").textContent=game.config.durationSeconds===0?"∞":`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function saveFinal(){if(game.saved)return;game.saved=true;storage.addScore({playerName:$("playerName").textContent,score:game.score,correct:game.correct,incorrect:game.incorrect,bestStreak:game.bestStreak,mode:game.config.mode,difficulty:game.config.difficulty})}
function finish(){if(game.finished)return;game.finished=true;clearInterval(timer);timer=null;saveFinal();$("feedback").className="ok";$("feedback").textContent="⏱️ Partida terminada. La puntuación se ha guardado.";renderRanking()}
function startTimer(){clearInterval(timer);timer=null;if(!game.config.durationSeconds)return;timer=setInterval(()=>{game.remaining--;update();if(game.remaining<=0)finish()},1000)}
$("spinButton").onclick=()=>{if(game.finished){game=createGame(config);update()}document.querySelectorAll(".slot").forEach(x=>x.classList.add("spinning"));setTimeout(()=>{document.querySelectorAll(".slot").forEach(x=>x.classList.remove("spinning"));showChallenge()},350);if(!timer)startTimer()};$("nextButton").onclick=showChallenge;
$("answerForm").onsubmit=e=>{e.preventDefault();if(!game.current||game.finished)return;const answer=$("answerInput").value,r=submit(game,answer);storage.addHistory({playerName:$("playerName").textContent,type:game.current.type,question:game.current.question,answer,expected:r.expected,correct:r.correct,formula:game.current.formula});$("feedback").className=r.correct?"ok":"bad";$("feedback").textContent=r.correct?`✅ Correcto · ${r.score} puntos`:`❌ La respuesta correcta es: ${r.expected}`;update()};
$("hintButton").onclick=()=>{if(game.current&&!game.finished)$("feedback").textContent=`Pista: cargas ${game.current.cation.charge>0?"+":""}${game.current.cation.charge} y ${game.current.anion.charge}`};$("explanationButton").onclick=()=>{if(!game.current)return;$("explanationPanel").innerHTML="<h3>Explicación</h3><ol>"+game.current.explanation.map(x=>`<li>${esc(x)}</li>`).join("")+`</ol><p><b>Estado de oxidación:</b> ${esc(game.current.stockName)}<br><b>Nomenclatura:</b> ${esc(game.current.systematicName)}</p>`;$("explanationPanel").classList.remove("hidden")};
$("saveConfiguration").onclick=()=>{config={durationSeconds:Number($("gameTime").value),mode:$("exerciseType").value,difficulty:$("difficulty").value,family:$("compoundFamily").value};storage.saveConfig(config);$("playerName").textContent=$("studentNameInput").value.trim()||"Alumno";clearInterval(timer);timer=null;game=createGame(config);update();view("student");showChallenge();startTimer()};$("resetGame").onclick=()=>{clearInterval(timer);timer=null;game=createGame(config);update();$("feedback").textContent=""};$("exportCsv").onclick=exportCSV;
function renderHistory(){const h=storage.getHistory().slice().reverse();$("historyList").innerHTML=h.length?`<table><tr><th>Alumno</th><th>Reto</th><th>Resultado</th></tr>${h.map(x=>`<tr><td>${esc(x.playerName)}</td><td>${esc(x.question)}</td><td>${x.correct?"✅":"❌"} ${esc(x.answer)}</td></tr>`).join("")}</table>`:"<p>Aún no hay ejercicios.</p>"}
function renderRanking(){const r=storage.ranking();$("rankingList").innerHTML=r.length?`<table><tr><th>#</th><th>Alumno</th><th>Total</th><th>Mejor</th></tr>${r.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.total}</td><td>${x.best}</td></tr>`).join("")}</table>`:"<p>Aún no hay puntuaciones.</p>"}$("clearHistory").onclick=()=>{if(confirm("¿Borrar el historial?")){storage.clearHistory();renderHistory()}};$("clearRanking").onclick=()=>{if(confirm("¿Borrar las puntuaciones?")){storage.clearScores();renderRanking()}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));const p=new URLSearchParams(location.search);if(p.get("teams")==="1")document.body.classList.add("teams");if(p.get("view"))view(p.get("view"));update();showChallenge();