export const CATIONS=[["Na","sodio",1],["K","potasio",1],["Ag","plata",1],["Mg","magnesio",2],["Ca","calcio",2],["Ba","bario",2],["Zn","zinc",2],["Al","aluminio",3],["Fe","hierro",2],["Fe","hierro",3],["Cu","cobre",1],["Cu","cobre",2],["Co","cobalto",2],["Co","cobalto",3],["NH4","amonio",1,true]].map(([symbol,name,charge,polyatomic=false])=>({symbol,name,charge,polyatomic}));
export const ANIONS=[["Cl","cloruro",-1],["F","fluoruro",-1],["Br","bromuro",-1],["I","yoduro",-1],["O","óxido",-2],["S","sulfuro",-2],["OH","hidróxido",-1,true],["NO3","nitrato",-1,true],["NO2","nitrito",-1,true],["SO4","sulfato",-2,true],["SO3","sulfito",-2,true],["CO3","carbonato",-2,true],["PO4","fosfato",-3,true],["PO3","fosfito",-3,true],["HSO4","hidrogenosulfato",-1,true],["HS","hidrogenosulfuro",-1,true],["HPO4","hidrogenofosfato",-2,true],["H2PO4","dihidrogenofosfato",-1,true],["CN","cianuro",-1,true]].map(([symbol,name,charge,polyatomic=false])=>({symbol,name,charge,polyatomic}));
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a),roman=n=>({1:"I",2:"II",3:"III",4:"IV"}[n]||String(n)),prefix=["","mono","di","tri","tetra","penta","hexa"];
export function subscripts(c,a){const g=gcd(c.charge,a.charge);return{c:Math.abs(a.charge)/g,a:Math.abs(c.charge)/g}}
const part=(ion,n)=>`${ion.polyatomic&&n>1?"("+ion.symbol+")":ion.symbol}${n>1?n:""}`;
export function generateFormula(c,a){const n=subscripts(c,a);return part(c,n.c)+part(a,n.a)}
export function getStockName(c,a){const variable=new Set(CATIONS.filter(x=>x.symbol===c.symbol).map(x=>x.charge)).size>1;return `${a.name} de ${c.name}${variable?`(${roman(c.charge)})`:""}`}
export function getSystematicName(c,a){const n=subscripts(c,a);if(a.polyatomic)return getStockName(c,a);let an=a.symbol==="O"?`${prefix[n.a]}óxido`:(n.a>1?`${prefix[n.a]}${a.name}`:a.name);let cat=n.c>1?`${prefix[n.c]}${c.name}`:c.name;return `${an} de ${cat}`}
export function formatIon(ion){const m=Math.abs(ion.charge),s=ion.charge>0?"+":"−";return ion.symbol+`<sup>${m===1?"":m}${s}</sup>`}
export function explainFormula(c,a){const n=subscripts(c,a);return[`El catión ${c.name} tiene carga +${c.charge}.`,`El anión ${a.name} tiene carga ${a.charge}.`,`Para que el compuesto sea neutro se necesitan ${n.c} catión(es) y ${n.a} anión(es).`,`La fórmula resultante es ${generateFormula(c,a)}.`]}
const normalize=s=>String(s??"").trim().toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
export const checkFormulaAnswer=(answer,expected)=>normalize(answer).replace(/[₀-₉]/g,x=>"₀₁₂₃₄₅₆₇₈₉".indexOf(x))===normalize(expected);
export const checkNameAnswer=(answer,expected)=>normalize(answer)===normalize(expected);
export function randomCompound({allowPolyatomic=true,difficulty="medium"}={}){let cs=CATIONS,as=ANIONS;if(!allowPolyatomic||difficulty==="easy"){cs=cs.filter(x=>!x.polyatomic);as=as.filter(x=>!x.polyatomic)}if(difficulty==="easy"){cs=cs.filter(x=>Math.abs(x.charge)<=2);as=as.filter(x=>Math.abs(x.charge)<=2)}const c=cs[Math.floor(Math.random()*cs.length)],a=as[Math.floor(Math.random()*as.length)];return{cation:c,anion:a,formula:generateFormula(c,a),stockName:getStockName(c,a),systematicName:getSystematicName(c,a),explanation:explainFormula(c,a)}}